apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: my-app
build:
  platforms: 
    - "linux/amd64"
  artifacts:
  - image: my-app
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  kustomize:
    paths:
    - k8s/overlays/local
deploy:
  kubectl: {}
portForward:
- resourceType: service
  resourceName: my-app
  port: 8080
  localPort: 8080
