apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app-prod

resources:
- ../../base
- namespace.yaml
- ingress.yaml

images:
- name: my-app
  newTag: v1.0.0

configMapGenerator:
- name: my-app-config
  behavior: merge
  literals:
  - LOG_LEVEL=warn
  - ENV=production
  - DATABASE_HOST=prod-db.example.com

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-app
  spec:
    replicas: 5
    template:
      spec:
        containers:
        - name: my-app
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"

patchesJson6902:
- target:
    version: v2
    kind: HorizontalPodAutoscaler
    name: my-app
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 5
    - op: replace
      path: /spec/maxReplicas
      value: 20